// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    CategorySelectInput: typeof import("./src/components/hobby/CategorySelectInput.vue")["default"];
    ElAlert: typeof import("element-plus/es")["ElAlert"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCalendar: typeof import("element-plus/es")["ElCalendar"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElProgress: typeof import("element-plus/es")["ElProgress"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    HobbyCalendar: typeof import("./src/components/hobby/HobbyCalendar.vue")["default"];
    HobbyCard: typeof import("./src/components/hobby/HobbyCard.vue")["default"];
    HobbyList: typeof import("./src/components/hobby/HobbyList.vue")["default"];
    HobbyTable: typeof import("./src/components/hobby/HobbyTable.vue")["default"];
    NewHobbyForm: typeof import("./src/components/hobby/NewHobbyForm.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheLogin: typeof import("./src/components/auth/TheLogin.vue")["default"];
    TheNavigation: typeof import("./src/components/TheNavigation.vue")["default"];
    TheRegister: typeof import("./src/components/auth/TheRegister.vue")["default"];
  }
}
